### ISSUE TITLE
[QGIS 3.34] AttributeError: type object 'QgsMessageBar' has no attribute 'SUCCESS'

### ISSUE THREAD

**Issue by Amalvir** [enricofer/autoSaver#24]
Hello,

There is an issue when the plugin try to inform the user that the save is successful in QGIS 3.34 : 

` self.iface.messageBar().pushMessage("Autosave", u"autosaved : "+layer.name(), level=qgis.gui.QgsMessageBar.SUCCESS, duration=3 )
             AttributeError: type object 'QgsMessageBar' has no attribute 'SUCCESS'`

Versions : 
Python : 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS : 3.34.3-Prizren Prizren, 47373234ac

**Comment by davidafuller01** [comment]
Confirmed. This plugin has not been updated in 26 months (https://github.com/enricofer/autoSaver/releases/tag/2.6). 

@enricofer - Has this project been abandoned?

**Comment by Marwe** [comment]
This has been fixed a while ago already (2.6 is rather old, but listed as stable on [Plugins](https://plugins.qgis.org/plugins/autoSaver/#plugin-versions)), maybe the release could be updated? 2.8 is tagged, but not yet released.

If you take the latest source the error should disappear. On Linux the plugin path is likely:
PROFILENAME=your_profilename
~/.local/share/QGIS/QGIS3/profiles/$PROFILENAME/python/plugins/autoSaver

**Comment by Amalvir** [comment]
Hi !
I manually update the source and it works !
But it seems that the plugin is not automatically updated by QGIS since the 2.6.
Thank you for your help
